// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: matrix.proto

package stubs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MultiplyBlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row      []int64 `protobuf:"fixed64,1,rep,packed,name=row,proto3" json:"row,omitempty"`
	Column   []int64 `protobuf:"fixed64,2,rep,packed,name=column,proto3" json:"column,omitempty"`
	RowId    int32   `protobuf:"varint,3,opt,name=rowId,proto3" json:"rowId,omitempty"`
	ColumnId int32   `protobuf:"varint,4,opt,name=columnId,proto3" json:"columnId,omitempty"`
}

func (x *MultiplyBlockRequest) Reset() {
	*x = MultiplyBlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matrix_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiplyBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiplyBlockRequest) ProtoMessage() {}

func (x *MultiplyBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matrix_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiplyBlockRequest.ProtoReflect.Descriptor instead.
func (*MultiplyBlockRequest) Descriptor() ([]byte, []int) {
	return file_matrix_proto_rawDescGZIP(), []int{0}
}

func (x *MultiplyBlockRequest) GetRow() []int64 {
	if x != nil {
		return x.Row
	}
	return nil
}

func (x *MultiplyBlockRequest) GetColumn() []int64 {
	if x != nil {
		return x.Column
	}
	return nil
}

func (x *MultiplyBlockRequest) GetRowId() int32 {
	if x != nil {
		return x.RowId
	}
	return 0
}

func (x *MultiplyBlockRequest) GetColumnId() int32 {
	if x != nil {
		return x.ColumnId
	}
	return 0
}

type MultiplyBlockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Element  int64 `protobuf:"fixed64,1,opt,name=element,proto3" json:"element,omitempty"`
	RowId    int32 `protobuf:"varint,2,opt,name=rowId,proto3" json:"rowId,omitempty"`
	ColumnId int32 `protobuf:"varint,3,opt,name=columnId,proto3" json:"columnId,omitempty"`
}

func (x *MultiplyBlockResponse) Reset() {
	*x = MultiplyBlockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matrix_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiplyBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiplyBlockResponse) ProtoMessage() {}

func (x *MultiplyBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matrix_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiplyBlockResponse.ProtoReflect.Descriptor instead.
func (*MultiplyBlockResponse) Descriptor() ([]byte, []int) {
	return file_matrix_proto_rawDescGZIP(), []int{1}
}

func (x *MultiplyBlockResponse) GetElement() int64 {
	if x != nil {
		return x.Element
	}
	return 0
}

func (x *MultiplyBlockResponse) GetRowId() int32 {
	if x != nil {
		return x.RowId
	}
	return 0
}

func (x *MultiplyBlockResponse) GetColumnId() int32 {
	if x != nil {
		return x.ColumnId
	}
	return 0
}

var File_matrix_proto protoreflect.FileDescriptor

var file_matrix_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x72,
	0x0a, 0x14, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x10, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x10, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x77, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x72, 0x6f, 0x77, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x49, 0x64, 0x22, 0x63, 0x0a, 0x15, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x10, 0x52, 0x07, 0x65, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x77, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x6f, 0x77, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x49, 0x64, 0x32, 0x4f, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x75,
	0x74, 0x65, 0x12, 0x44, 0x0a, 0x13, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x52, 0x6f,
	0x77, 0x42, 0x79, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x15, 0x2e, 0x6d, 0x75, 0x6c, 0x74,
	0x69, 0x70, 0x6c, 0x79, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x73, 0x74, 0x75,
	0x62, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_matrix_proto_rawDescOnce sync.Once
	file_matrix_proto_rawDescData = file_matrix_proto_rawDesc
)

func file_matrix_proto_rawDescGZIP() []byte {
	file_matrix_proto_rawDescOnce.Do(func() {
		file_matrix_proto_rawDescData = protoimpl.X.CompressGZIP(file_matrix_proto_rawDescData)
	})
	return file_matrix_proto_rawDescData
}

var file_matrix_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_matrix_proto_goTypes = []interface{}{
	(*MultiplyBlockRequest)(nil),  // 0: multiplyBlockRequest
	(*MultiplyBlockResponse)(nil), // 1: multiplyBlockResponse
}
var file_matrix_proto_depIdxs = []int32{
	0, // 0: compute.multiplyRowByColumn:input_type -> multiplyBlockRequest
	1, // 1: compute.multiplyRowByColumn:output_type -> multiplyBlockResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_matrix_proto_init() }
func file_matrix_proto_init() {
	if File_matrix_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_matrix_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiplyBlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matrix_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiplyBlockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_matrix_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_matrix_proto_goTypes,
		DependencyIndexes: file_matrix_proto_depIdxs,
		MessageInfos:      file_matrix_proto_msgTypes,
	}.Build()
	File_matrix_proto = out.File
	file_matrix_proto_rawDesc = nil
	file_matrix_proto_goTypes = nil
	file_matrix_proto_depIdxs = nil
}
